package com.tedu.cgb.team.common.entity;

import java.io.Serializable;
import java.util.Date;

public class Cart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carts.id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carts.user_id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carts.product_id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carts.total
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carts.creation_date
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table carts
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carts.id
     *
     * @return the value of carts.id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carts.id
     *
     * @param id the value for carts.id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carts.user_id
     *
     * @return the value of carts.user_id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carts.user_id
     *
     * @param userId the value for carts.user_id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carts.product_id
     *
     * @return the value of carts.product_id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carts.product_id
     *
     * @param productId the value for carts.product_id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carts.total
     *
     * @return the value of carts.total
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carts.total
     *
     * @param total the value for carts.total
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carts.creation_date
     *
     * @return the value of carts.creation_date
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carts.creation_date
     *
     * @param creationDate the value for carts.creation_date
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carts
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", productId=").append(productId);
        sb.append(", total=").append(total);
        sb.append(", creationDate=").append(creationDate);
        sb.append("]");
        return sb.toString();
    }
}