package com.tedu.cgb.team.common.entity;

import java.io.Serializable;
import java.util.Date;

public class Logger implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logger.id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logger.username
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logger.operation
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logger.ip
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logger.creation_date
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logger.id
     *
     * @return the value of logger.id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logger.id
     *
     * @param id the value for logger.id
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logger.username
     *
     * @return the value of logger.username
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logger.username
     *
     * @param username the value for logger.username
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logger.operation
     *
     * @return the value of logger.operation
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logger.operation
     *
     * @param operation the value for logger.operation
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logger.ip
     *
     * @return the value of logger.ip
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logger.ip
     *
     * @param ip the value for logger.ip
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logger.creation_date
     *
     * @return the value of logger.creation_date
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logger.creation_date
     *
     * @param creationDate the value for logger.creation_date
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", operation=").append(operation);
        sb.append(", ip=").append(ip);
        sb.append(", creationDate=").append(creationDate);
        sb.append("]");
        return sb.toString();
    }
}