package com.tedu.cgb.team.common.entity;

import java.io.Serializable;
import java.util.Date;

public class OrderProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_products.id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_products.order_id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_products.product_id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_products.total
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_products.creation_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_products.id
     *
     * @return the value of order_products.id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_products.id
     *
     * @param id the value for order_products.id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_products.order_id
     *
     * @return the value of order_products.order_id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_products.order_id
     *
     * @param orderId the value for order_products.order_id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_products.product_id
     *
     * @return the value of order_products.product_id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_products.product_id
     *
     * @param productId the value for order_products.product_id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_products.total
     *
     * @return the value of order_products.total
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_products.total
     *
     * @param total the value for order_products.total
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_products.creation_date
     *
     * @return the value of order_products.creation_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_products.creation_date
     *
     * @param creationDate the value for order_products.creation_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", productId=").append(productId);
        sb.append(", total=").append(total);
        sb.append(", creationDate=").append(creationDate);
        sb.append("]");
        return sb.toString();
    }
}