package com.tedu.cgb.team.common.entity;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.address
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.post
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiver
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_message
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private String userMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.creation_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private Date payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.delivery_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private Date deliveryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.confirm_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private Date confirmDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.userId
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.state
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.address
     *
     * @return the value of orders.address
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.address
     *
     * @param address the value for orders.address
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.post
     *
     * @return the value of orders.post
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.post
     *
     * @param post the value for orders.post
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver
     *
     * @return the value of orders.receiver
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver
     *
     * @param receiver the value for orders.receiver
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_message
     *
     * @return the value of orders.user_message
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public String getUserMessage() {
        return userMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_message
     *
     * @param userMessage the value for orders.user_message
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setUserMessage(String userMessage) {
        this.userMessage = userMessage == null ? null : userMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.creation_date
     *
     * @return the value of orders.creation_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.creation_date
     *
     * @param creationDate the value for orders.creation_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_date
     *
     * @return the value of orders.pay_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_date
     *
     * @param payDate the value for orders.pay_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.delivery_date
     *
     * @return the value of orders.delivery_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public Date getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.delivery_date
     *
     * @param deliveryDate the value for orders.delivery_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.confirm_date
     *
     * @return the value of orders.confirm_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public Date getConfirmDate() {
        return confirmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.confirm_date
     *
     * @param confirmDate the value for orders.confirm_date
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setConfirmDate(Date confirmDate) {
        this.confirmDate = confirmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.userId
     *
     * @return the value of orders.userId
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.userId
     *
     * @param userid the value for orders.userId
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.state
     *
     * @return the value of orders.state
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.state
     *
     * @param state the value for orders.state
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", address=").append(address);
        sb.append(", post=").append(post);
        sb.append(", receiver=").append(receiver);
        sb.append(", userMessage=").append(userMessage);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", payDate=").append(payDate);
        sb.append(", deliveryDate=").append(deliveryDate);
        sb.append(", confirmDate=").append(confirmDate);
        sb.append(", userid=").append(userid);
        sb.append(", state=").append(state);
        sb.append("]");
        return sb.toString();
    }
}