package com.tedu.cgb.team.common.entity;

import java.io.Serializable;

public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.id
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.price
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.context
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.decs
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    private String decs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.img
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.category_id
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table products
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.id
     *
     * @return the value of products.id
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.id
     *
     * @param id the value for products.id
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.price
     *
     * @return the value of products.price
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.price
     *
     * @param price the value for products.price
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.context
     *
     * @return the value of products.context
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.context
     *
     * @param context the value for products.context
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.decs
     *
     * @return the value of products.decs
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public String getDecs() {
        return decs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.decs
     *
     * @param decs the value for products.decs
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public void setDecs(String decs) {
        this.decs = decs == null ? null : decs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.img
     *
     * @return the value of products.img
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.img
     *
     * @param img the value for products.img
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.category_id
     *
     * @return the value of products.category_id
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.category_id
     *
     * @param categoryId the value for products.category_id
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Sep 20 19:05:22 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", price=").append(price);
        sb.append(", context=").append(context);
        sb.append(", decs=").append(decs);
        sb.append(", img=").append(img);
        sb.append(", categoryId=").append(categoryId);
        sb.append("]");
        return sb.toString();
    }
}