package com.tedu.cgb.team.common.dao;

import com.tedu.cgb.team.common.entity.Logger;
import com.tedu.cgb.team.common.entity.LoggerExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LoggerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    int countByExample(LoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    int deleteByExample(LoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    int insert(Logger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    int insertSelective(Logger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    List<Logger> selectByExample(LoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    Logger selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") Logger record, @Param("example") LoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    int updateByExample(@Param("record") Logger record, @Param("example") LoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    int updateByPrimaryKeySelective(Logger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logger
     *
     * @mbg.generated Thu Sep 19 23:27:09 CST 2019
     */
    int updateByPrimaryKey(Logger record);
}