package com.tedu.cgb.team.common.dao;

import com.tedu.cgb.team.common.entity.OrderProduct;
import com.tedu.cgb.team.common.entity.OrderProductExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrderProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    int countByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    int deleteByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    int insert(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    int insertSelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    List<OrderProduct> selectByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    OrderProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderProduct record, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    int updateByExample(@Param("record") OrderProduct record, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    int updateByPrimaryKeySelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sat Sep 21 08:56:55 CST 2019
     */
    int updateByPrimaryKey(OrderProduct record);
}